import OsamaElzeroImg from "/src/assets/osama-elzero.jpeg";
import MohammedAbusreaImg from "/src/assets/mohammed-abosre3.jpg";
import AhmedFathyImg from "/src/assets/ahmed-fathy.jpg";
import AlmdrasaImg from "/src/assets/almdrasa.jpg";
import W3SchollsImg from "/src/assets/w3schools.jpg";
import PostOneImg from "/src/assets/post-1.jpeg";
import PostTwoImg from "/src/assets/post-2.jpg";
import PostThreeImg from "/src/assets/post-3.jpg";
import PostFiveImg from "/src/assets/post-5.jpg";
import PostSixImg from "/src/assets/post-6.jpg";

export const Posts = [
  {
    id: 1,
    userImg: OsamaElzeroImg,
    userName: "Osama Elzero",
    userFollowers: "255.325",
    postTime: "8h",
    postTitle:
      "This repo contains a treasure trove of JavaScript articles , Link In Comments .",
    img: PostOneImg,
    imgDisplay: "block",
    reactsNum: 412,
    commentsNum: 30,
    repostsNum: 21,
    ifLikeDisplay: "none",
    ifLikeImg: "",
    ifLikeName: "",
    ifLikeLink: "",
    ifCommentDisplay: "none",
    ifCommentImg: "",
    ifCommentName: "",
    ifCommentLink: "",
  },
  {
    id: 2,
    userImg: MohammedAbusreaImg,
    userName: "Mohammed Abusrea",
    userFollowers: "92.542",
    postTime: "2d",
    postTitle:
      "should i learn JavaScript or TypeScript ?! Video Link In Comments..",
    img: PostTwoImg,
    reactsNum: 168,
    commentsNum: 13,
    repostsNum: 6,
    ifLikeDisplay: "block",
    ifLikeImg: OsamaElzeroImg,
    ifLikeName: "Osama Elzero",
    ifLikeLink: "",
    ifCommentDisplay: "none",
    ifCommentImg: "",
    ifCommentName: "",
    ifCommentLink: "",
  },
  {
    id: 3,
    userImg: AhmedFathyImg,
    userName: "Ahmed Fathy",
    userFollowers: "121.389",
    postTime: "3d",
    postTitle: "important live on youtube after two hours ..",
    img: PostThreeImg,
    reactsNum: 150,
    commentsNum: 5,
    repostsNum: 24,
    ifLikeDisplay: "none",
    ifLikeImg: "",
    ifLikeName: "",
    ifLikeLink: "",
    ifCommentDisplay: "none",
    ifCommentImg: "",
    ifCommentName: "",
    ifCommentLink: "",
  },
  {
    id: 4,
    userImg: OsamaElzeroImg,
    userName: "Osama Elzero",
    userFollowers: "255.325",
    postTime: "4d",
    postTitle: "Nothing Is Everything !",
    img: "",
    imgDisplay: "none",
    reactsNum: 420,
    commentsNum: 20,
    repostsNum: 33,
    ifLikeDisplay: "none",
    ifLikeImg: "",
    ifLikeName: "",
    ifLikeLink: "",
    ifCommentDisplay: "none",
    ifCommentImg: "",
    ifCommentName: "",
    ifCommentLink: "",
  },
  {
    id: 5,
    userImg: AlmdrasaImg,
    userName: "Almdrasa",
    userFollowers: "129.595",
    postTime: "5d",
    postTitle:
      "are you wait for the new ai course ? type your opinion in comments",
    img: "",
    imgDisplay: "none",
    reactsNum: 45,
    commentsNum: 9,
    repostsNum: 2,
    ifLikeDisplay: "none",
    ifLikeImg: "",
    ifLikeName: "",
    ifLikeLink: "",
    ifCommentDisplay: "block",
    ifCommentImg: AhmedFathyImg,
    ifCommentName: "Ahmed Fathy",
    ifCommentLink: "",
  },
  {
    id: 6,
    userImg: W3SchollsImg,
    userName: "W3Scholls",
    userFollowers: "1.429.135",
    postTime: "1w",
    postTitle: "It's funny because it's true 💚.",
    img: PostFiveImg,
    imgDisplay: "block",
    reactsNum: 781,
    commentsNum: 39,
    repostsNum: 178,
    ifLikeDisplay: "none",
    ifLikeImg: "",
    ifLikeName: "",
    ifLikeLink: "",
    ifCommentDisplay: "none",
    ifCommentImg: "",
    ifCommentName: "",
    ifCommentLink: "",
  },
  {
    id: 7,
    userImg: MohammedAbusreaImg,
    userName: "Mohammed Abusrea",
    userFollowers: "92.542",
    postTime: "1w",
    postTitle: "Who can relate? 👋🏼 Tag a friend that needs a ☕️- break!",
    img: PostSixImg,
    reactsNum: 132,
    commentsNum: 6,
    repostsNum: 8,
    ifLikeDisplay: "none",
    ifLikeImg: "",
    ifLikeName: "",
    ifLikeLink: "",
    ifCommentDisplay: "none",
    ifCommentImg: "",
    ifCommentName: "",
    ifCommentLink: "",
  },
  {
    id: 8,
    userImg: W3SchollsImg,
    userName: "W3Scholls",
    userFollowers: "1.429.135",
    postTime: "2w",
    postTitle:
      "Write a few lines today that your future slef will thank you for !",
    img: "",
    imgDisplay: "none",
    reactsNum: 1051,
    commentsNum: 28,
    repostsNum: 246,
    ifLikeDisplay: "block",
    ifLikeImg: MohammedAbusreaImg,
    ifLikeName: "Mohammed Abusrea",
    ifLikeLink: "",
    ifCommentDisplay: "none",
    ifCommentImg: "",
    ifCommentName: "",
    ifCommentLink: "",
  },
];
